CREATE TABLE tblhRehabilitacionInnovar (
    idEHREvent INT,
    FechaCita DATE,
    idAction INT,
    Accion NVARCHAR(MAX),
    idPaciente INT,
    DocumentoPaciente NVARCHAR(255),
    Tipo_Documento NVARCHAR(50),
    NombrePaciente NVARCHAR(MAX),
    FechaMuerte DATE,
    Ciudad NVARCHAR(100),
    BarrioPaciente NVARCHAR(100),
    LocalidadPaciente NVARCHAR(100),
    DireccionPaciente NVARCHAR(MAX),
    CelularPaciente NVARCHAR(20),
    TelefonoPaciente NVARCHAR(20),
    Sede NVARCHAR(MAX),
    idEncounter INT,
    idContrato INT,
    Contrato NVARCHAR(MAX),
    DestinoEgresoAsistencial NVARCHAR(MAX),
    DestinoEgresoAdministrativo NVARCHAR(MAX),
    DetalleDestinoEgresoAdministrativo NVARCHAR(MAX),
    FechaEgresoAdministrativo DATE,
    idProfesional INT,
    NombreProfesional NVARCHAR(MAX),
    idDiagnostico INT,
    CodigoDiagnosticoPrincipal NVARCHAR(50),
    DiagnosticoPrincipal NVARCHAR(MAX),
    idAutorizacion INT,
    PaqueteEvento NVARCHAR(MAX),
    CUPS NVARCHAR(50),
    Autorizacion NVARCHAR(MAX),
    CantidadServiciosAutorizados INT,
    VigenciaAutorizacion DATE,
    FechaInicio DATE,
    FechaFin DATE,
    TFOrdenadas INT,
    TLOrdenadas INT,
    TOOrdenadas INT,
    TROrdenadas INT,
    TRPrioritariasOrdenadas INT,
    Barthel INT,
    FechaCitaEjecutada DATE,
    PaqueteEventoEjecutada NVARCHAR(MAX),
    TFEjecutadas INT,
    ProfesionalTF NVARCHAR(MAX),
    TLEjecutadas INT,
    ProfesionalTL NVARCHAR(MAX),
    TOEjecutadas INT,
    ProfesionalTO NVARCHAR(MAX),
    TREjecutadas INT,
    ProfesionalTR NVARCHAR(MAX)
)create index ix_tblhRehabilitacionInnovar on tblhRehabilitacionInnovar (
	idEHREvent,
	idAction,
	idPaciente,
	idEncounter,
	idContrato,
	idDiagnostico,
	idAutorizacion
);